# Generated by Django 6.0.7 on 2026-09-03 09:36

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_architecture_configuration"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingContract",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authority", models.CharField(max_length=512, unique=True)),
                ("provenance", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperatingContractBinding",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "update_policy",
                    models.CharField(choices=[("pinned", "Pinned"), ("follow-latest", "Follow latest")], max_length=32),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperatingContractGuidance",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_revision", models.CharField(max_length=64)),
                ("authority", models.CharField(max_length=512)),
                ("position", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OperatingContractReference",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(choices=[("policy", "Policy"), ("architecture", "Architecture")], max_length=32),
                ),
                ("target_id", models.CharField(max_length=255)),
                ("authority", models.CharField(max_length=512)),
                ("target_revision", models.CharField(max_length=128)),
                ("position", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OperatingContractRevision",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="projectrecord",
            name="projects_project_record_unique",
        ),
        migrations.AddField(
            model_name="operatingcontractbinding",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operating_contract_binding",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="operatingcontractguidance",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operating_contract_references",
                to="records.record",
            ),
        ),
        migrations.AddField(
            model_name="operatingcontractrevision",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="projects.operatingcontract"
            ),
        ),
        migrations.AddField(
            model_name="operatingcontractreference",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_references",
                to="projects.operatingcontractrevision",
            ),
        ),
        migrations.AddField(
            model_name="operatingcontractguidance",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guidance_references",
                to="projects.operatingcontractrevision",
            ),
        ),
        migrations.AddField(
            model_name="operatingcontractbinding",
            name="bound_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bindings",
                to="projects.operatingcontractrevision",
            ),
        ),
        migrations.RemoveField(
            model_name="projectrecord",
            name="project",
        ),
        migrations.AddConstraint(
            model_name="operatingcontractrevision",
            constraint=models.UniqueConstraint(
                fields=("contract", "version"), name="projects_operating_contract_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcontractreference",
            constraint=models.UniqueConstraint(
                fields=("revision", "kind", "target_id"), name="projects_operating_contract_reference_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcontractreference",
            constraint=models.UniqueConstraint(
                fields=("revision", "position"), name="projects_operating_contract_reference_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcontractguidance",
            constraint=models.UniqueConstraint(
                fields=("revision", "record"), name="projects_operating_contract_guidance_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcontractguidance",
            constraint=models.UniqueConstraint(
                fields=("revision", "position"), name="projects_operating_contract_guidance_position_unique"
            ),
        ),
        migrations.DeleteModel(
            name="ProjectRecord",
        ),
    ]
