# Generated by Django 6.0.7 on 2026-09-03 11:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_operatingcontract_operatingcontractbinding_and_more"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceScope",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidance_scopes",
                        to="projects.project",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="guidance_scopes", to="records.record"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("project", "record"), name="projects_guidance_scope_record_unique"),
                    models.UniqueConstraint(
                        fields=("project", "position"), name="projects_guidance_scope_position_unique"
                    ),
                ],
            },
        ),
    ]
