# Generated by Django 6.0.7 on 2026-09-03 14:11

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_guidancescope"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceRelationship",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Prerequisite"),
                            ("containment", "Containment"),
                            ("refinement", "Refinement"),
                            ("escalation", "Escalation"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidance_relationships",
                        to="projects.project",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_guidance_relationships",
                        to="records.record",
                    ),
                ),
                (
                    "target_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_guidance_relationships",
                        to="records.record",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "source_record", "target_record", "kind"),
                        name="projects_guidance_relationship_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ("prerequisite", "containment", "refinement", "escalation"))),
                        name="projects_guidance_relationship_kind_valid",
                    ),
                ],
            },
        ),
    ]
