# Generated by Django 6.0.7 on 2026-09-04 08:42

from pathlib import Path

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


def move_locations_to_workspace_bindings(apps, schema_editor) -> None:
    Project = apps.get_model("projects", "Project")
    WorkspaceBinding = apps.get_model("projects", "WorkspaceBinding")
    roots: set[str] = set()
    bindings = []
    for project in Project.objects.iterator():
        root = str(Path(project.root).expanduser().resolve())
        architecture_root = str(Path(project.architecture_root).expanduser().resolve())
        title = Path(root).name
        if not title:
            raise RuntimeError(f"Project title cannot be derived from workspace root: {root}")
        if root in roots:
            raise RuntimeError(f"Projects resolve to the same workspace root: {root}")
        if not Path(architecture_root).is_relative_to(root):
            raise RuntimeError(f"Project architecture root is outside its workspace root: {root}")
        roots.add(root)
        Project.objects.filter(pk=project.id).update(title=title)
        bindings.append(
            WorkspaceBinding(
                project_id=project.id,
                root=root,
                architecture_root=architecture_root,
                revision=1,
            )
        )
    WorkspaceBinding.objects.bulk_create(bindings)


def restore_locations_to_projects(apps, schema_editor) -> None:
    Project = apps.get_model("projects", "Project")
    WorkspaceBinding = apps.get_model("projects", "WorkspaceBinding")
    for workspace in WorkspaceBinding.objects.order_by("project_id", "root").iterator():
        Project.objects.filter(pk=workspace.project_id).update(
            root=workspace.root,
            architecture_root=workspace.architecture_root,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_guidancerelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WorkspaceBinding",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("root", models.CharField(max_length=1024, unique=True)),
                ("architecture_root", models.CharField(max_length=1024)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_bindings",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(move_locations_to_workspace_bindings, restore_locations_to_projects),
        migrations.RemoveField(
            model_name="project",
            name="architecture_root",
        ),
        migrations.RemoveField(
            model_name="project",
            name="root",
        ),
    ]
