# Generated by Django 6.0.7 on 2026-09-27 17:14

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_workspace_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureContractPublication",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("authority", models.CharField(max_length=512)),
                ("revision", models.CharField(max_length=64)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architecture_contract_publications",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchitectureContractUnit",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("diagram_set_id", models.CharField(max_length=22)),
                ("source_root", models.CharField(max_length=1024)),
                ("coverage", models.CharField(max_length=32)),
                ("position", models.PositiveIntegerField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="projects.architecturecontractpublication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchitectureContractExclusion",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("reason", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="projects.architecturecontractunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchitectureContractDiagram",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagram_id", models.CharField(max_length=22)),
                ("diagram_revision", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=32)),
                ("scope", models.CharField(max_length=32)),
                ("kind", models.CharField(max_length=64)),
                ("snapshot_version", models.PositiveIntegerField()),
                ("registry_fingerprint", models.CharField(max_length=64)),
                ("snapshot_digest", models.CharField(max_length=64)),
                ("snapshot", models.JSONField()),
                ("position", models.PositiveIntegerField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagrams",
                        to="projects.architecturecontractunit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="architecturecontractpublication",
            constraint=models.UniqueConstraint(
                fields=("project", "version"), name="projects_arch_contract_publication_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractpublication",
            constraint=models.UniqueConstraint(
                fields=("project", "revision"), name="projects_arch_contract_publication_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractunit",
            constraint=models.UniqueConstraint(
                fields=("publication", "key"), name="projects_arch_contract_unit_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractunit",
            constraint=models.UniqueConstraint(
                fields=("publication", "position"), name="projects_arch_contract_unit_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("coverage__in", ("closed", "declared"))),
                name="projects_arch_contract_unit_coverage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractexclusion",
            constraint=models.UniqueConstraint(
                fields=("unit", "path"), name="projects_arch_contract_exclusion_path_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractexclusion",
            constraint=models.UniqueConstraint(
                fields=("unit", "position"), name="projects_arch_contract_exclusion_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractdiagram",
            constraint=models.UniqueConstraint(
                fields=("unit", "diagram_id"), name="projects_arch_contract_diagram_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractdiagram",
            constraint=models.UniqueConstraint(
                fields=("unit", "position"), name="projects_arch_contract_diagram_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractdiagram",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("tree", "uml", "entity"))),
                name="projects_arch_contract_diagram_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturecontractdiagram",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope__in", ("complete", "focused", "reference"))),
                name="projects_arch_contract_diagram_scope_valid",
            ),
        ),
    ]
