# Generated by Django 6.0.7 on 2026-07-30 10:38

import django.db.models.deletion
import pgvector.django.extensions
import pgvector.django.vector
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content_schema', models.JSONField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorySchemaRevision',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content_schema', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_revisions', to='records.category')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'version'), name='records_category_schema_revision_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('schema_version', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='records.category')),
                ('tags', models.ManyToManyField(related_name='records', to='records.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=512)),
                ('language', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='records.record')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'path'), name='records_resource_record_path_unique')],
            },
        ),
    ]
