# Generated by Django 6.0 for Enclosure actor authorization.

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.CharField(max_length=255)),
                ("actor_kind", models.CharField(max_length=32)),
                ("operation_id", models.CharField(max_length=255)),
                ("target", models.TextField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("correlation_id", models.CharField(max_length=255)),
                ("requested_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor_id", "actor_kind", "operation_id", "payload_digest"],
                        name="security_approval_scope_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("execution_id", models.CharField(db_index=True, max_length=255)),
                ("actor_id", models.CharField(db_index=True, max_length=255)),
                ("actor_kind", models.CharField(max_length=32)),
                ("operation_id", models.CharField(db_index=True, max_length=255)),
                ("target", models.TextField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("phase", models.CharField(max_length=32)),
                ("decision", models.CharField(max_length=32)),
                ("outcome", models.CharField(max_length=32)),
                ("reason_code", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(db_index=True, max_length=255)),
                ("safe_metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "permissions": (
                    ("invoke_read", "Can invoke read operations"),
                    ("invoke_mutation", "Can invoke mutation operations"),
                    ("invoke_destructive", "Can invoke destructive operations"),
                    ("approve_operation", "Can approve destructive operations"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ApprovalResolution",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("decision", models.CharField(max_length=32)),
                ("decider_actor_id", models.CharField(max_length=255)),
                ("decided_at", models.DateTimeField()),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution",
                        to="security.approvalrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalConsumption",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("execution_id", models.CharField(max_length=255, unique=True)),
                ("consumed_at", models.DateTimeField()),
                (
                    "resolution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumption",
                        to="security.approvalresolution",
                    ),
                ),
            ],
        ),
    ]
