class EnclosureError(Exception): ...


class DomainError(EnclosureError): ...


class ServiceUnavailableError(DomainError): ...


class GatewayTimeoutError(DomainError): ...


class InternalExecutionError(EnclosureError): ...
