# Generated by Django 6.0.7 on 2026-08-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='interactions',
        ),
    ]
